name: Build OpenWrt snapshot

on:
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: master
  FEEDS: "packages luci routing telephony freifunk waller"

jobs:
  build:
    name: Build ${{ matrix.config }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: False
      matrix:
        config:
          - "R7800"
          - "EX6150v2"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Cache sources
      uses: davidsbond/cache@master
      with:
        path: dl/
        key: Sources
        update: True

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get -y install libncurses-dev
        #TARGET=$(echo ${{ matrix.targets }} | cut -d "/" -f 1)
        #SUBTARGET=$(echo ${{ matrix.targets }} | cut -d "/" -f 2)
        #echo "TARGET=$TARGET" >> "$GITHUB_ENV"
        #echo "SUBTARGET=$SUBTARGET" >> "$GITHUB_ENV"
        sudo timedatectl set-timezone "Asia/Hong_Kong"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt

    - name: Apply patches to base feed
      working-directory: /openwrt
      run: |
        [ -d $GITHUB_WORKSPACE/patches/base ] && PATCHES="$( ls $GITHUB_WORKSPACE/patches/base/*.patch )"
        for i in $PATCHES; do
          echo -e "\n---- Applying patch $(basename $i) ----\n"
          git apply -v --whitespace=nowarn $i
        done

    - name: Update feeds
      working-directory: /openwrt
      run: ./scripts/feeds update -a

    - name: Apply patches to feeds
      working-directory: /openwrt
      run: |
        for feed in $FEEDS; do
          if [ -d "$GITHUB_WORKSPACE/openwrt/feeds/$feed" ] && [ -d "$GITHUB_WORKSPACE/patches/$feed" ]; then
            echo -e "\n---- Applying patches to $feed feed ----\n"
            ( 
              cd "$GITHUB_WORKSPACE/openwrt/feeds/$feed";
                for i in $( ls "$GITHUB_WORKSPACE/patches/$feed"/*.patch ); do
                  echo  -e "\n---- Applying patch $(basename $i) ----\n"
                  git apply -v --whitespace=nowarn $i
                done 
            )
          fi
        done

    - name: Update & Install feeds
      working-directory: /openwrt
      run: |
        ./scripts/feeds update -i
        ./scripts/feeds install -a
