name: Build OpenWrt snapshot

on:
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: master
  FEEDS: "packages luci routing telephony freifunk waller"

jobs:
  build:
    name: Build ${{ matrix.device }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: False
      matrix:
        include:
          - device: "netgear_r7800"
            target: "ipq806x"
            subtarget: "generic"
            config: "R7800"
          - device: "netgear_ex6150v2"
            target: "ipq40xx"
            subtarget: "generic"
            config: "EX6150v2"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Cache sources
      uses: davidsbond/cache@master
      with:
        path: dl/
        key: Sources
        update: True

    - name: Cache config
      uses: davidsbond/cache@master
      with:
        path: config/
        key: ${{ matrix.device }}
        update: True

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get -y install libncurses-dev
        echo "TARGET=${{ matrix.target }}" >> "$GITHUB_ENV"
        echo "SUBTARGET=${{ matrix.subtarget }}" >> "$GITHUB_ENV"
        sudo timedatectl set-timezone "Asia/Hong_Kong"

    - name: Clone source code
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt

    - name: Save version info
      working-directory: openwrt
      run: |
        mkdir -p config
        date -Is > config/versiontime
        VERSION=$REPO_BRANCH-$(./scripts/getver.sh)-$(date +%Y%m%d-%H%M)
        echo $VERSION > config/version
        cat config/versiontime
        cat config/version

    - name: Apply patches to base feed
      working-directory: openwrt
      run: |
        [ -d $GITHUB_WORKSPACE/patches/base ] && PATCHES="$( ls $GITHUB_WORKSPACE/patches/base/*.patch )"
        for i in $PATCHES; do
          echo -e "\n---- Applying patch $(basename $i) ----\n"
          git apply -v --whitespace=nowarn $i
        done

    - name: Update feeds
      working-directory: openwrt
      run: ./scripts/feeds update -a

    - name: Apply patches to feeds
      working-directory: openwrt
      run: |
        for feed in $FEEDS; do
          if [ -d "$GITHUB_WORKSPACE/openwrt/feeds/$feed" ] && [ -d "$GITHUB_WORKSPACE/patches/$feed" ]; then
            echo -e "\n---- Applying patches to $feed feed ----\n"
            ( 
              cd "$GITHUB_WORKSPACE/openwrt/feeds/$feed";
                for i in $( ls "$GITHUB_WORKSPACE/patches/$feed"/*.patch ); do
                  echo  -e "\n---- Applying patch $(basename $i) ----\n"
                  git apply -v --whitespace=nowarn $i
                done 
            )
          fi
        done

    - name: Update & Install feeds
      working-directory: openwrt
      run: |
        ./scripts/feeds update -i
        ./scripts/feeds install -a

    - name: Set configuration
      working-directory: openwrt
      env:
        CONFIG_FILES: "common_hnyman.config.init common_override.config.init ${{ matrix.config }}.config.init"
      run: |
        curl "https://downloads.openwrt.org/snapshots/targets/${{ matrix.target }}/${{ matrix.subtarget }}/config.buildinfo" > .config

        echo -e "\n# Use "make defconfig" to expand this to a full .config\n\n" > .config.init
        for i in $CONFIG_FILES; do
          if [ -f "$GITHUB_WORKSPACE/$i" ]; then
            echo -e "\n\n\n## $i ##\n\n" >> .config.init
            cat "$GITHUB_WORKSPACE/$i" >> .config.init
          fi
        done
        cp -fpR .config.init .config
        make defconfig
        ./scripts/diffconfig.sh > .diffconfig

        #echo -e "\n---- config post-defconfig ----\n"
        #cat .config
        #echo -e "\n---- config post-defconfig ----\n"

        #echo -e "\n---- diffconfig ----\n"
        #cat .diffconfig
        #echo -e "\n---- diffconfig ----\n"

        mkdir -p $GITHUB_WORKSPACE/config
        if [ -f "$GITHUB_WORKSPACE/config/${{ matrix.device }}.diffconfig" ]; then
          diff -uprN "$GITHUB_WORKSPACE/config/${{ matrix.device }}.diffconfig" .diffconfig > .diffconfig.diff
          echo -e "\n---- diffconfig diff ----\n"
          cat .diffconfig.diff
          echo -e "\n---- diffconfig diff ----\n"
          cp -fpR .diffconfig.diff $GITHUB_WORKSPACE/config/${{ matrix.device }}.diffconfig.diff
        fi
        if [ -f "$GITHUB_WORKSPACE/config/${{ matrix.device }}.config" ]; then
          diff -uprN "$GITHUB_WORKSPACE/config/${{ matrix.device }}.config" .config > .config.diff
          echo -e "\n---- config diff ----\n"
          cat .config.diff
          echo -e "\n---- config diff ----\n"
          cp -fpR .config.diff $GITHUB_WORKSPACE/config/${{ matrix.device }}.config.diff
        fi
        
        cp -fpR .config $GITHUB_WORKSPACE/config/${{ matrix.device }}.config
        cp -fpR .diffconfig $GITHUB_WORKSPACE/config/${{ matrix.device }}.diffconfig
