name: Release OpenWrt Firmwares

on:
  workflow_dispatch:

env:
  WORKFLOW_NAME: "main.yml"

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-20.04
    steps:
    - name: Retieve version artifact
      run: |
        URL="$GITHUB_API_URL/repos/$GITHUB_REPOSITORY/actions/workflows/$WORKFLOW_NAME/runs?per_page=1&page=1&status=success"
        HEADERS="--header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' --header 'content-type: application/json'"
        WORKFLOW_RUN_ID="$(curl $HEADERS --url $URL | jq '.workflow_runs[0].id')"
        echo $WORKFLOW_RUN_ID
        curl $HEADERS --url $URL
