name: Release OpenWrt Firmwares

on:
  workflow_dispatch:

env:
  WORKFLOW_NAME: "main.yml"

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-20.04
    steps:
    - name: Download version
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: main.yml
        workflow_conclusion: success
        name: version
        path: version

    - name: Check
      working-directory: version
      run: |
        ls -l
        cat timestamp
        cat commitid
        cat openwrt_commitid
        cat openwrt_version
